apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecrets
metadata:
  labels:
    app.kubernetes.io/name: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: cluster
spec: {}
